#!/bin/bash

if [ ! -f .venv/bin/activate ]; then
  echo "No venv found, creating venv"
  python3 -m venv .venv
fi

source .venv/bin/activate
echo "Installing requirements"
pip install -r requirements.txt --quiet

if [ ! -f .env ]; then
   echo "Please set your API key in .env-key"
   exit 1
fi


