# Generated by Django 5.1.2 on 2024-10-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_data', '0002_alter_financialdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prediction', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_data.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'date'], name='ai_integrat_symbol__e56cd7_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
