# Generated by Django 5.1.2 on 2024-10-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'ordering': ['symbol', 'date']},
        ),
    ]
